<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-INQUNRP" ignored="2" name="Deposite(failed)" tests="2" failures="1" timestamp="2021-05-29T17:19:00 EDT" time="0.021" errors="0">
  <testcase name="selectAmountTest" time="0.001" classname="com.ChaseBankTestNgListeners.DepositeTest">
    <failure type="java.lang.AssertionError" message="expected [4] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [5]
at com.ChaseBankTestNgListeners.DepositeTest.selectAmountTest(DepositeTest.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- selectAmountTest -->
  <testcase name="confrimAmountTest" time="0.0" classname="com.ChaseBankTestNgListeners.DepositeTest">
    <skipped/>
  </testcase> <!-- confrimAmountTest -->
  <testcase name="logOutTest" time="0.0" classname="com.ChaseBankTestNgListeners.DepositeTest">
    <ignored/>
  </testcase> <!-- logOutTest -->
  <testcase name="checkBalanceTest" time="0.0" classname="com.ChaseBankTestNgListeners.DepositeTest">
    <ignored/>
  </testcase> <!-- checkBalanceTest -->
</testsuite> <!-- Deposite(failed) -->
